---
openapi: 3.0.0
info:
  title: Auditorium Booking Service
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/AndriiDolinskyi/ABookingAPI/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /user:
    get:
      tags:
      - User
      summary: Get all users
      description: Get all users
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user_w_id'
    post:
      tags:
      - User
      summary: Create new user
      description: Create new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_w_id'
        "400":
          description: Invalid body, Valid body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: User with such email already exists
  /user/{userId}:
    get:
      tags:
      - User
      summary: Get user data
      description: Get user data
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_w_id'
        "400":
          description: Invalid Id
        "404":
          description: User not found
  /auditorium:
    get:
      tags:
      - Auditorium
      summary: Get all auditoriums
      description: Get all auditoriums
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/auditorium_w_id'
    post:
      tags:
      - Auditorium
      summary: Add auditorium to DB
      description: Add auditorium to DB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auditorium'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auditorium'
        "400":
          description: Invalid body, Valid body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auditorium'
        "409":
          description: Auditorium with such number already exists
  /auditorium/{auditoriumid}:
    get:
      tags:
      - Auditorium
      summary: Get auditorium by ID
      description: Get auditorium by ID
      parameters:
      - name: auditoriumid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: auditorium body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auditorium_w_id'
        "400":
          description: Invalid Id
        "404":
          description: auditorium not found
  /booking:
    get:
      tags:
      - Booking
      summary: Get all bookings
      description: Get all bookings
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/booking_w_id'
    post:
      tags:
      - Booking
      summary: Add new booking to DB
      description: Add new booking to DB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/booking'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/booking_w_id'
        "400":
          description: Invalid body, Valid body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/booking'
        "406":
          description: Auditorium on this time are already booked
          content:
            application/json:
              schema:
                type: string
                example: Auditorium on this time are already booked
        "409":
          description: Such booking number already exists
  /booking/{bookingid}:
    get:
      tags:
      - Booking
      summary: Get booking by ID
      description: Get booking by ID
      parameters:
      - name: bookingid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: booking body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/booking_w_id'
        "404":
          description: booking not found
    put:
      tags:
      - Booking
      summary: Edit booking
      parameters:
      - name: bookingid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Edit booking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/booking'
        "404":
          description: Booking not found
        "406":
          description: Auditorium on this time are already booked
          content:
            application/json:
              schema:
                type: string
                example: Auditorium on this time are already booked
    delete:
      tags:
      - Booking
      summary: Delete booking
      parameters:
      - name: bookingid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Booking has been deleted
        "404":
          description: Booking not found
  /booking/user/{userid}:
    get:
      tags:
      - Booking
      summary: Get bookings by user's ID
      description: Get bookings by user's ID
      parameters:
      - name: userid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: array of bookings this user made
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/booking_w_id'
        "404":
          description: User not found
        "401":
          description: User is not authorized
components:
  schemas:
    user:
      type: object
      properties:
        Name:
          type: string
        Email:
          type: string
          example: smth@com
        Password:
          type: string
          format: password
      nullable: false
    user_w_id:
      type: object
      properties:
        Id:
          type: integer
          example: 1
        Name:
          type: string
        Email:
          type: string
          example: smth@com
        Password:
          type: string
          format: password
      nullable: false
    auditorium:
      type: object
      properties:
        Number_of_auditorium:
          type: integer
          description: the number of auditorium
          example: 3
    auditorium_w_id:
      type: object
      properties:
        Id:
          type: integer
          description: ID from DB
          example: 1
        Number_of_auditorium:
          type: integer
          description: the number of auditorium
          example: 3
    booking:
      type: object
      properties:
        user's_id:
          type: integer
          description: user, who booked auditorium (his/her id)
          example: 1
        auditorium_id:
          type: integer
          description: auditorium, which was booked by the user (its id)
          example: 1
        booking_date_time:
          type: string
          format: date-time
          example: 2020-09-29T09:12:33.001Z
        expire_date_time:
          type: string
          format: date-time
          example: 2020-09-29T09:19:00.001Z
    booking_w_id:
      type: object
      properties:
        Id:
          type: integer
          description: ID from DB
          example: 1
        user's_id:
          type: integer
          description: user, who booked auditorium (his/her id)
          example: 1
        auditorium_id:
          type: integer
          description: auditorium, which was booked by the user (its id)
          example: 1
        booking_date_time:
          type: string
          format: date-time
          example: 2020-09-29T09:12:33.001Z
        expire_date_time:
          type: string
          format: date-time
          example: 2020-09-29T09:19:00.001Z
